---
title: "Final"
output: html_document
date: "2026-07-01"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Inputting the data
```{r}
library(tidyverse)
library(readxl)
library(ggpubr)

salmon <- read_excel("~/Downloads/Coho Larvae Measurements_Issaquah.xlsx")
```

Organizing the data
```{r}
salmon <- salmon |> rename(eye_area = 'Eye Area (square um)_ed', 
                           yolk_area = 'Yolk Area (square um)_ed', 
                           length_analysis = 'Total Length (um)_ed',
                           DPH = "days post hatch")

clean_salmon <- salmon |> filter_out(
  str_detect(Notes, "Endpoint | "))

subset_salmon_eye <- clean_salmon |> select(treatment, DPH, eye_area) |> drop_na(eye_area)

subset_salmon_yolk <- clean_salmon |> select(treatment, DPH, yolk_area) |> drop_na(yolk_area)

subset_salmon_length <- clean_salmon |> select(treatment, DPH, length_analysis) |> drop_na(length_analysis)


x1 <- subset_salmon_eye |> filter(DPH == "6") |> select(treatment, eye_area)
y1 <- subset_salmon_eye |> filter(DPH == "0") |> select(treatment, eye_area)

x2 <- subset_salmon_yolk |> filter(DPH == "6") |> select(treatment, yolk_area)
y2 <- subset_salmon_yolk |> filter(DPH == "0") |> select(treatment, yolk_area)

x3 <- subset_salmon_length |> filter(DPH == "6") |> select(treatment, length_analysis)
y3 <- subset_salmon_length |> filter(DPH == "0") |> select(treatment, length_analysis)
```

My function
```{r}
make_myboxplot <- function(data, yvar, ylab, title, comparisons){
  
  ymax <- max(data[[yvar]], na.rm = TRUE)
  
  ggboxplot(
    data,
    x = "treatment",
    y = yvar,
    fill = "treatment",
    add = "mean_ci",
    outlier.shape = NA
  ) +
    geom_jitter(width = 0.08, alpha = 0.6, size = 2) +
    stat_compare_means(
      method = "anova",
      label.y = ymax * 1.15
    ) +
    stat_compare_means(
      comparisons = comparisons,
      method = "t.test",
      label = "p.signif",
      step.increase = 0.08
    ) +
    labs(
      title = title,
      x = "6PPDq concentration",
      y = ylab
    ) +
    theme_classic(base_size = 14) +
    theme(
      plot.title = element_text(face = "bold", hjust = 0.5),
      axis.title = element_text(face = "bold"),
      legend.position = "none"
    )
}
```

Making the boxplots
```{r}
my_comparisons <- list(c("Control", "Low"), c("Control", "Medium"), c("Control", "High"),
                       c("Low", "Medium"), c("Low", "High"), c("Medium", "High"))

my_comparisons_y <- list(c("Control", "Medium"))

make_myboxplot(x1, "eye_area",
               "Eye Area (um^2)",
               "Effect of 6PPDq Exposure on Eye Area 6 days post hatch",
               my_comparisons)

make_myboxplot(y1, "eye_area",
               "Eye Area (um^2)",
               "Effect of 6PPDq Exposure on Eye Area 0 days post hatch",
               my_comparisons)

make_myboxplot(x2, "yolk_area",
               "yolk area (um^2)",
               "Effect of 6PPDq Exposure on Yolk Area 6 days post hatch",
               my_comparisons)

make_myboxplot(y2, "yolk_area",
               "yolk area (um^2)",
               "Effect of 6PPDq Exposure on Yolk Area 0 days post hatch",
               my_comparisons)

make_myboxplot(x3, "length_analysis",
               "length (um)",
               "Effect of 6PPDq Exposure on Fish Length 6 days post hatch",
               comparisons = NULL)

make_myboxplot(y3, "length_analysis",
               "length (um)",
               "Effect of 6PPDq Exposure on Fish Length 0 days post hatch",
               my_comparisons)
```


